In [2]:
import pandas as pd
import numpy as np

# Meta ensemble

In [183]:
catboost = pd.read_csv('catBoost.csv')
catboost.drop('Unnamed: 0', axis=1, inplace=True)
catboost

,userID,assessmentItemID,Timestamp,test_seq,user_correct_answer,user_acc,test_mean,test_sum,before_tag,testId,answerCode,KnowledgeTag,ori_index,diff,mean,item,id,prediction
0,0,A020172001,0.782360,0,0.231464,0.614726,0.404889,0.348972,1.0,A020000172,1,8132,584,600.0,0.262506,A020172001,0,0.633244
1,0,A020172002,0.782360,1,0.232108,0.615385,0.404889,0.348972,1.0,A020000172,1,8132,585,9.0,0.262506,A020172002,1,0.424049
2,0,A020172003,0.782361,2,0.232753,0.616041,0.404889,0.348972,1.0,A020000172,1,8132,586,17.0,0.262506,A020172003,2,0.479781
3,0,A020172004,0.782362,3,0.233398,0.616695,0.404889,0.348972,1.0,A020000172,1,8132,587,33.0,0.262506,A020172004,3,0.766173
4,0,A020172005,0.782363,4,0.234043,0.617347,0.404889,0.348972,1.0,A020000172,0,8132,588,34.0,0.262506,A020172005,4,0.830062
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2266581,7441,A030071005,0.430289,4,0.000645,0.250000,0.533838,0.321830,0.0,A030000071,0,438,2266581,24.0,0.247513,A030071005,2266581,0.225069
2266582,7441,A040165001,0.641132,0,0.000645,0.200000,0.521932,0.243117,1.0,A040000165,1,8836,2266582,600.0,0.251825,A040165001,2266582,0.382234
2266583,7441,A040165002,0.641132,1,0.001289,0.333333,0.521932,0.243117,1.0,A040000165,1,8836,2266583,11.0,0.251825,A040165002,2266583,0.656654
2266584,7441,A040165003,0.641134,2,0.001934,0.428571,0.521932,0.243117,1.0,A040000165,1,8836,2266584,46.0,0.251825,A040165003,2266584,0.724498
2266585,7441,A040165004,0.641136,3,0.002579,0.500000,0.521932,0.243117,1.0,A040000165,1,8836,2266585,73.0,0.251825,A040165004,2266585,0.545960

In [185]:
lgbm = pd.read_csv('lgbm.csv')
lgbm.drop('Unnamed: 0', axis=1, inplace=True)
lgbm

,userID,assessmentItemID,testId,answerCode,Timestamp,KnowledgeTag,user_correct_answer,user_total_answer,user_acc,test_mean,test_sum,tag_mean,tag_sum,diff,mean,id,prediction
0,0.0,5354.0,975.0,1.0,0.228242,618.0,0.000000,0.000000,0.000000,0.947683,0.456378,0.955022,0.058117,-1.0,345.923228,0,0.996821
1,0.0,5355.0,975.0,1.0,0.228242,619.0,0.000674,0.000538,1.000000,0.947683,0.456378,0.913187,0.283729,3.0,59.008799,1,0.929109
2,0.0,5356.0,975.0,1.0,0.228243,619.0,0.001348,0.001076,1.000000,0.947683,0.456378,0.913187,0.283729,8.0,59.008799,2,0.983010
3,0.0,5357.0,975.0,1.0,0.228243,619.0,0.002022,0.001614,1.000000,0.947683,0.456378,0.913187,0.283729,7.0,59.008799,3,0.969973
4,0.0,5358.0,975.0,1.0,0.228243,619.0,0.002695,0.002152,1.000000,0.947683,0.456378,0.913187,0.283729,7.0,59.008799,4,0.968364
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2266581,7441.0,2373.0,456.0,0.0,0.429723,375.0,0.000674,0.002152,0.250000,0.662590,0.321830,0.689706,0.262511,24.0,160.096973,2266581,0.442040
2266582,7441.0,3909.0,748.0,1.0,0.640796,784.0,0.000674,0.002690,0.200000,0.655109,0.243117,0.697874,0.204770,600.0,162.502079,2266582,0.501394
2266583,7441.0,3910.0,748.0,1.0,0.640797,784.0,0.001348,0.003228,0.333333,0.655109,0.243117,0.697874,0.204770,11.0,162.502079,2266583,0.482639
2266584,7441.0,3911.0,748.0,1.0,0.640798,784.0,0.002022,0.003765,0.428571,0.655109,0.243117,0.697874,0.204770,46.0,162.502079,2266584,0.546269
2266585,7441.0,3912.0,748.0,1.0,0.640801,784.0,0.002695,0.004303,0.500000,0.655109,0.243117,0.697874,0.204770,73.0,162.502079,2266585,0.540245

In [186]:
lightgcn = pd.read_csv('/opt/ml/input/code/dkt_sh/dkt/lightgcn/lightgcn_train_data.csv')
lightgcn_pred = pd.read_csv('/opt/ml/input/code/dkt_sh/dkt/lightgcn/output/best_auc_submission.csv')

lightgcn = pd.concat([lightgcn, lightgcn_pred], axis=1)
lightgcn

,Unnamed: 0,userID,assessmentItemID,testId,answerCode,Timestamp,KnowledgeTag,ori_index,id,prediction
0,0,0,A060001001,A060000001,1,2020-03-24 00:17:11,7224,0,0,0.982906
1,1,0,A060001002,A060000001,1,2020-03-24 00:17:14,7225,1,1,0.982236
2,2,0,A060001003,A060000001,1,2020-03-24 00:17:22,7225,2,2,0.976035
3,3,0,A060001004,A060000001,1,2020-03-24 00:17:29,7225,3,3,0.981615
4,4,0,A060001005,A060000001,1,2020-03-24 00:17:36,7225,4,4,0.977336
...,...,...,...,...,...,...,...,...,...,...
2266581,2266581,7441,A030071005,A030000071,0,2020-06-05 06:50:21,438,2266581,2266581,0.077971
2266582,2266582,7441,A040165001,A040000165,1,2020-08-21 01:06:39,8836,2266582,2266582,0.930627
2266583,2266583,7441,A040165002,A040000165,1,2020-08-21 01:06:50,8836,2266583,2266583,0.918145
2266584,2266584,7441,A040165003,A040000165,1,2020-08-21 01:07:36,8836,2266584,2266584,0.860402
2266585,2266585,7441,A040165004,A040000165,1,2020-08-21 01:08:49,8836,2266585,2266585,0.882755

In [187]:
catboost = catboost.sort_values('ori_index')
lightgcn = lightgcn.sort_values('ori_index')

lightgcn.id = lightgcn.ori_index
catboost.id = catboost.ori_index

catboost = catboost.reset_index()
catboost.drop('index', inplace=True, axis=1)

In [188]:
models_output = pd.DataFrame()
models_output['catboost'] = catboost['prediction']
models_output['lightgcn'] = lightgcn['prediction']
models_output['lgbm'] = lgbm['prediction']
models_output['answerCode'] = lgbm.answerCode

In [189]:
models_output

         catboost  lightgcn      lgbm  answerCode
0        0.959606  0.982906  0.996821         1.0
1        0.954233  0.982236  0.929109         1.0
2        0.962274  0.976035  0.983010         1.0
3        0.980417  0.981615  0.969973         1.0
4        0.969545  0.977336  0.968364         1.0
...           ...       ...       ...         ...
2266581  0.225069  0.077971  0.442040         0.0
2266582  0.382234  0.930627  0.501394         1.0
2266583  0.656654  0.918145  0.482639         1.0
2266584  0.724498  0.860402  0.546269         1.0
2266585  0.545960  0.882755  0.540245         1.0

[2266586 rows x 4 columns]

# 평균 합

In [190]:
from sklearn.metrics import roc_auc_score
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

In [191]:
y = models_output.pop('answerCode')
X_train, X_test, y_train, y_test = train_test_split(
    models_output, y, test_size=0.3, random_state=42)

In [192]:
train_mean_hap = (X_train.catboost + X_train.lightgcn + X_train.lgbm)/3
ensem_train_acc = accuracy_score(y_train, np.where(train_mean_hap >= 0.5, 1, 0))
ensem_train_auc = roc_auc_score(y_train, train_mean_hap)

test_mean_hap = (X_test.catboost + X_test.lightgcn + X_test.lgbm)/3
ensem_valid_acc = accuracy_score(y_test, np.where(test_mean_hap >= 0.5, 1, 0))
ensem_valid_auc = roc_auc_score(y_test, test_mean_hap)

In [59]:
print(f'TRAIN MEAN_HAP AUC : {ensem_train_auc} ACC : {ensem_train_acc}')
print(f'VALID MEAN_HAP AUC : {ensem_valid_auc} ACC : {ensem_valid_acc}')

TRAIN MEAN_HAP AUC : 0.8758356944268971 ACC : 0.8125084299229174
VALID MEAN_HAP AUC : 0.8755556581128001 ACC : 0.8120580726378578

In [193]:
ensem_train_acc = accuracy_score(y_train, np.where(X_train.catboost >= 0.5, 1, 0))
ensem_train_auc = roc_auc_score(y_train, X_train.catboost)

ensem_valid_acc = accuracy_score(y_test, np.where(X_test.catboost >= 0.5, 1, 0))
ensem_valid_auc = roc_auc_score(y_test, X_test.catboost)

print(f'TRAIN CATBOOST AUC : {ensem_train_auc} ACC : {ensem_train_acc}')
print(f'VALID CATBOOST AUC : {ensem_valid_auc} ACC : {ensem_valid_acc}')

TRAIN CATBOOST AUC : 0.8417647812028548 ACC : 0.7899130851311916
VALID CATBOOST AUC : 0.8414804370762919 ACC : 0.7898558184406509

# 메타 모델

In [67]:
# 메타러닝
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier

meta_model = LogisticRegression()
#meta_model = GaussianNB()
#meta_model = DecisionTreeClassifier()
meta_model.fit(X_train, y_train)

meta_train_pred = meta_model.predict_proba(X_train)

meta_train_pred = meta_train_pred[:,-1]
meta_train_acc = accuracy_score(y_train, np.where(meta_train_pred >= 0.5, 1, 0))
meta_train_auc = roc_auc_score(y_train, meta_train_pred)

## valid
meta_valid_pred = meta_model.predict_proba(X_test)
meta_valid_pred = meta_valid_pred[:,-1]
meta_valid_acc = accuracy_score(y_test, np.where(meta_valid_pred >= 0.5, 1, 0))
meta_valid_auc = roc_auc_score(y_test, meta_valid_pred)

In [68]:
print(f'TRAIN MEAN_HAP AUC : {ensem_train_auc} ACC : {ensem_train_acc}')
print(f'VALID MEAN_HAP AUC : {ensem_valid_auc} ACC : {ensem_valid_acc}\n')

print(f'TRAIN MEAN_HAP AUC : {meta_train_auc} ACC : {meta_train_acc}')
print(f'VALID MEAN_HAP AUC : {meta_valid_auc} ACC : {meta_valid_acc}')

TRAIN MEAN_HAP AUC : 0.8758356944268971 ACC : 0.8125084299229174
VALID MEAN_HAP AUC : 0.8755556581128001 ACC : 0.8120580726378578

TRAIN MEAN_HAP AUC : 0.891330327418207 ACC : 0.830237424445831
VALID MEAN_HAP AUC : 0.8910922533794383 ACC : 0.8303087167782393

# inference에 메타 모델 적용

In [73]:
lgbm = pd.read_csv('sunny_lgbm.csv')
lstmattn_gcn = pd.read_csv('brill_lstmattn_gcn.csv')
catboost = pd.read_csv('truth_catboost.csv')
lightgcn = pd.read_csv('sunny_lightgcn.csv')

In [71]:
X_train

         catboost  lightgcn      lgbm
2021291  0.804529  0.917813  0.665100
655482   0.903059  0.943581  0.779585
471661   0.486197  0.167058  0.370271
798601   0.909288  0.947220  0.843714
1210613  0.835794  0.855259  0.763987
...           ...       ...       ...
732180   0.798097  0.944981  0.865164
110268   0.930331  0.986613  0.917423
1692743  0.146812  0.138926  0.113200
2229084  0.190216  0.170693  0.515371
2219110  0.784333  0.541653  0.689968

[1586610 rows x 3 columns]

In [75]:
infer = pd.DataFrame()
infer['catboost'] = catboost.prediction
infer['lightgcn'] = lightgcn.prediction
infer['lgbm'] = lgbm.prediction
infer

     catboost  lightgcn      lgbm
0    0.790801  0.420943  0.768696
1    0.861991  0.865882  0.720709
2    0.351468  0.547949  0.335367
3    0.793809  0.723556  0.906585
4    0.349015  0.203509  0.738634
..        ...       ...       ...
739  0.010406  0.136036  0.022470
740  0.860940  0.681501  0.737194
741  0.880051  0.867673  0.722316
742  0.808275  0.259134  0.601318
743  0.700335  0.614289  0.400679

[744 rows x 3 columns]

In [81]:
meta_pred = meta_model.predict_proba(infer)
meta_pred = meta_pred[:,-1]

ensem_0511 = lgbm.copy()
ensem_0511.prediction = meta_pred

In [85]:
ensem_0511

      id  prediction
0      0    0.448747
1      1    0.910936
2      2    0.449926
3      3    0.837284
4      4    0.143359
..   ...         ...
739  739    0.044343
740  740    0.784816
741  741    0.912925
742  742    0.220414
743  743    0.619818

[744 rows x 2 columns]

In [89]:
len(ensem_0511[ensem_0511.prediction > 0.5])

356

In [178]:
ensem_0511.to_csv('ensem_0511.csv')